### ISSUE TITLE
"transitionend" event not trigger when computer or browser slow

### ISSUE THREAD

**Issue by cdoneshot** [vuejs/vue#10758]
### Version
2.5.17

### Reproduction link
**This is no reproduction, because it's not a frequent problem**
[https://no-reproduce-code.io](https://no-reproduce-code.io)

### Steps to reproduce
This is some of my code
```html
<template>
  <transition name="dialog">
    <div class="dialog-container mask-layer"
         v-show="visible">
         <!-- dialog content -->
    </div>
  </transition>
</template>
```
```js
 data(){
     return {
       visible: true
    }
 },
 methods: {
    // this methods will be called when user click some button
    close() {
     this.visible = false;
      const { parentNode } = this.$el;
      let transitionendTriggered = false;

      console.log('close method be called');
      this.$el.addEventListener('transitionend', () => {
        parentNode.removeChild(this.$el);
        transitionendTriggered = true;
        console.log('transitionend trigger');
      });
      // to fix transitionend not trigger
      // this.timer = setTimeout(() => {
      //   if (!transitionendTriggered) {
      //     parentNode.removeChild(this.$el);
      //   }
      // }, 500);
    },
   ...other methods
}
```

```scss
  .dialog-container{
    &.dialog-enter-active {
      transition: all 0.3s ease-in;
    }
    &.dialog-leave-active {
      transition: all 0.3s ease-out;
      opacity: 0;
   }
    &.dialog-enter {
      opacity: 0;
    }
    &.dialog-leave {
      opacity: 0;
    }
  }
```

### What is expected?
transitionend be triggered

### What is actually happening?
transitionend not be triggered sometimes

---
**This is not a frequent problem. Most of the time it will run fine, but I noticed that it often occurs whenever my computer or browser is running slowly. I added some consoles to my code, then observed the print results and found that transitionend was not triggered.**

- works fine
![image](https://user-images.githubusercontent.com/20412044/67537285-45d91180-f70d-11e9-9c9e-b71c902f5882.png)

- transitionend not triggered
![image](https://user-images.githubusercontent.com/38171689/67537142-b6336300-f70c-11e9-837b-875296077b6d.png)
