### ISSUE TITLE
Noscript error when deployed on Kubernetes with Nginx Ingress

### ISSUE THREAD

**Issue by brandonguigo** [vuejs/vue#11800]
### Version
2.6.11

### Reproduction link
[https://github.com/TallamQuiz/tallam](https://github.com/TallamQuiz/tallam)

### Steps to reproduce
Deploy an EKS Kubernetes Cluster With Nginx Ingress and NLB.
Build the docker image : 
`
FROM node:lts-alpine
RUN npm install -g http-server

WORKDIR /app
COPY package*.json ./

RUN npm install
COPY . .

RUN npm run build

EXPOSE 8080
CMD [ "http-server", "dist", "-p", "80"]
`
Deploy the following service/deployment : 
```
apiVersion: v1
kind: Service
metadata:
  name: backoffice-service
  namespace: internal
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: app-backoffice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-backoffice
  namespace: internal
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-backoffice
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-backoffice
    spec:
      containers:
        - name: app-backoffice
          image: backoffice:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
```
Deploy the Ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-tallam-internal
  namespace: internal
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
        - path: /backoffice/*
          backend:
              serviceName: backoffice-service
              servicePort: 80
```
See that the no script error is shown

### What is expected?
the project should be served on /backoffice and should be displayed

### What is actually happening?
The div app is empty and the no script error is raised while JS is enable in browser

---
I want to run a vue app on an EKS Cluster with Nginx Ingress and NLB for balancing.
I have tried to set the baseUrl to /backoffice like in the ingress but it doesn't change a thing.
The browser gets 200 on all the files but the app div is empty and the no script error is raised. Also, an unexpected < is found in the console.
