### ISSUE TITLE
transition-group  v-move  do not work when list remove 

### ISSUE THREAD

**Issue by 874435441** [vuejs/vue#11998]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/sggst?file=/src/App.vue](https://codesandbox.io/s/sggst?file=/src/App.vue)

### Steps to reproduce
click remove button

### What is expected?
after  num dispose animation end , move animation start

### What is actually happening?
 no move animation 

---
click  add button, it works just i want. num enter animation start, move animation delay 1s start.
but click remove button, after num leave animation end, move animation not happen.
when  .list-complete-leave-active  add position:absolute, click remove button odd animation happen, leave animation and move animation both delay 1s,  and transform animation also become odd，it move to lower left

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

I think this is what you are looking for

```css
.list-complete-move {
  transition: all 1s;
  /* transition-delay: 1s; */
}
.list-complete-move:not(.list-complete-leave-active){
  transition-delay: 1s;
}
```
