### ISSUE TITLE
<percentage> in css @property is handled incorrectly after run build

### ISSUE THREAD

**Issue by llliuyang** [vuejs/vue#13113]
### Version
2.7.15

### Reproduction link
[codepen.io](https://codepen.io/llliuyang/pen/xxMgwbJ)

### Steps to reproduce
npm run build

### What is expected?
```css
@property --p {
  syntax: '<percentage>';
  inherits: false;
  initial-value: 0%;
}
```

### What is actually happening?
```css
@property --p {
  syntax: '<percentage>';
  inherits: false;
  initial-value: 0;
}
```

---
The value of  'initial-value' property changes from 0% to 0, causing the animation  to fail.
I've tried vue 2.6 upgrades to the latest 2.7.15 all have this problem,but  it's correct in vue3.x

```
@vue/cli: 5.0.8
```
