### ISSUE TITLE
v-if vorks oddly with transition if lacking leave-transition

### ISSUE THREAD

**Issue by Twiknight** [vuejs/vue#2027]
I'm not sure if it is a bug or a feature.

code here:
http://jsfiddle.net/Lzpp0xrf/

double click the button and an additional label will be displayed.

**Comment by Atinux** [comment]
Hi @Twiknight 

`v-if` works nice, your problem comes from the CSS, you have to declare how your element should like like when it is hidden (.expand-leave):
```css
.expand-leave {
  height: 0;
  padding: 0 10px;
  opacity: 0;
}
```

Working example: http://jsfiddle.net/Atinux/w8h036rs/
