### ISSUE TITLE
Feature request : transition-direction property

### ISSUE THREAD

**Issue by Grafikart** [vuejs/vue#2534]
Reversing a transition can be a bit tricky forcing us to use additional classes since VueJS don't accept interpolations within `transition=""`

"transition-direction" property
=======================

This property would accept 3 values : 

- **0**, don't do any transition
- **1** (default)
- **-1**, `-leave` and `-enter` classes are swaped
  - The element being removed get the class `transition-enter`
  - The element being added get the class `transition-leave`

This property is optional, so this feature don't break compatibility

What it avoids ?
===================

If we want to reverse a transition, since we can't name our transition, we have to use an additional class to define the direction.

```css
.slide-transition{
  transform: translateX(0);
  transition: all 0.3s;
}

.slide-transition.off{
  transform: translateX(-100%);
  transition-duration: 0s;
}

.slide-leave, .reversed.slide-enter{
  transform: translateX(-100%);
}

.slide-enter, .reversed.slide-leave{
  transform: translateX(100%);
}
```

And then 

```html
<div v-for="item in items" transition="slide" :class="classDirection">{{ item }}</div>
```

With `classDirection` being `null`, `reversed` or `off`
