### ISSUE TITLE
Inline block justify layout is not work when using `v-for` directive

### ISSUE THREAD

**Issue by bammoo** [vuejs/vue#2964]
### Vue.js version
1.0.23

### Reproduction Link
This issue was asked as a question here: http://forum.vuejs.org/topic/4026/inline-block-justify-layout-is-not-work-when-using-v-for-directive/2

Inline block justify layout is not work when using v-for directive, example here
http://codepen.io/jfxiao07/pen/WwWdLg

The following code is pasted from the pen

```html
  <ul class="Grid">
    <li v-for="i in 3">
      {{i}}
    </li>
  </ul>
```

```css
.Grid {
  text-align: justify;
}
.Grid li {
  display: inline-block;
}
```

### What is actually happening?
Seems `text-align:justify` not work when spaces between tags are removed
