### ISSUE TITLE
[feature request] specify insert position for entering element in transition

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue#3654]
I am using vue 2.0 transition system + vue-router 2.0 to implement ios-style page switching animation. 

```html 
<transition :name="transitionName">
  <router-view/>
</transition>
```

The requirements include:

1. `transitionName = 'slidein'`, the new page slide in from the right, covering the old page, the old page does not move
1. When going back, `transitionName = 'slideout'`, the new page slide out to the right, revealing the old page, the old page does not move

Requirement 1 is easy 

```css
.slidein-enter {
  transform: translate3d(100%, 0, 0)
}
.slidein-enter-active {
  transition: transform .4s ease-out;
}
```

But for 2, this doesn't work

```css
.slideout-leave-active {
  transform: translate3d(100%, 0, 0);
  transition: transform .4s ease-out;
}
```

The old page shows immediately and the sliding transition of the new page is not observed. I believe this is because the entering element is always appended to the `router-view` container so that the leaving element is covered by the immediately entered(the old) one.

So perhaps we can add a prop to `transition` so that we can specify where to insert the entering element, e.g.

```html
<transition entering="prepend"/>
<transition entering="append"/>
```
