### ISSUE TITLE
ios 下（尤其是webView）Vue项目浏览器白屏遮罩粗劣的解决方案

### ISSUE THREAD

**Issue by veaba** [vuejs/vue#7229]
### Version
2.5.9

### Reproduction link
[https://github.com/veaba/vue-project-bug](https://github.com/veaba/vue-project-bug)

### Steps to reproduce
【警告，最好是】
【复现步骤】
1、在app 顶级文件中，这样写代码 
```css
html, body {
  width: 100%;
  height: 100%;
  margin: 0;
  padding: 0;
  position: relative;
}
.container{
  position: relative;
  width: 100%;
  height: 100%;
  background: #fff;
}

```

2、在ios（iphone6） 上，A页面滚动超过一屏幕高度后，一屏 高度后，跳到B页面，再返回会得到以下结果
![img_0139](https://user-images.githubusercontent.com/8652596/33892132-fadbfa28-df92-11e7-95a6-01259528b482.PNG)

### What is expected?
【原本期望】：
1、一切正常的浏览器访问

### What is actually happening?
【BUG必现】：
1、实际上得到一个必现的bug，A页面大约1200px 自顶部到底部有一大片空白会遮盖住

2、必须点击页面才会让空白消失

---
【解决方案，粗劣】
1、这样更改样式
```css
html, body {
  width: 100%;
  height: 100%;
  margin: 0;
  padding: 0;
  position: relative;
}
.container {
  width: 100%;
  height: 100%;
  background: #fff;
  overflow: scroll;
  -webkit-overflow-scrolling: touch;
  position: absolute;
  left:0;
  top:0;
}

```

2、原因是，经过排查，发现在ios 机器上使用webview 开发Vue项目时候，go history (-1)，无法将body 的高度拉掉，使得遮住，触发轻点击，方可消除该遮罩

3、解决的理论：用于最重要的html 容器是container，然而因为设置html、body高度是100%，从而造成了 container 撑开父级，但浏览器默认滚动的scroll 并不是 container（可能我这里认识是错的），而是body，某些因素，造成返回history 后，无法复原（ios 的锅），为此，我们将 container 进行了绝对定位，并让它重新成为 scroll 的对象，从而解决问题

4、container 这样写
 ```css
.container {
  width: 100%;
  height: 100%;
  background: #fff;
  overflow: scroll;
  -webkit-overflow-scrolling: touch;
  position: absolute;
  left:0;
  top:0;
}
```

5、不足之处
- 如果使劲拉开高度，还是出出现一些不尽如人意的地方，比如会折叠
- 如果不加 -webkit-overflow-scrolling: touch;  ，滑动时候会比较生硬(加了之后，解决了大部分的生硬问题，但依然不是最好的)
