### ISSUE TITLE
Use transition for router-view  and component use v-fcuse, the animation  lose frame

### ISSUE THREAD

**Issue by fyuan1992** [vuejs/vue#7779]
# Use transition for router-view  and component use v-fcuse, the animation  lose frame
use vue-cli
## app.vue
```html
<div id="app">
    <transition :name="transitionName">
        <router-view></router-view>
    </transition>
</div>
```
```javascript
export default {
  name: 'App',
  data () {
    return {
      transitionName: 'slide-left'
    }
  },
  watch: {
    '$route' (to, from) {
      const toDepth = to.path.split('/').length
      const fromDepth = from.path.split('/').length
      console.log(toDepth + '------' + fromDepth)
      this.transitionName = toDepth < fromDepth ? 'slide-right' : 'slide-left'
      console.log(this.transitionName)
    }
  }
}
```
```css
.slide-left-enter-active,
.slide-left-leave-active,
.slide-right-enter-active,
.slide-right-leave-active {
  will-change: transform;
  transition: all 1000ms;
  height: 100%;
  top: 0;
  position: absolute;
  backface-visibility: hidden;
  perspective: 1000;
}
.slide-left-enter {
  opacity: 0;
  transform: translate3d(100%, 0, 0);
}
.slide-left-leave-active {
  opacity: 0;
  transform: translate3d(-100%, 0, 0);
}
.slide-right-enter {
  opacity: 0;
  transform: translate3d(-100%, 0, 0);
}
.slide-right-leave-to {
  opacity: 0;
  transform: translate3d(100%, 0, 0);
}
```
## router component 
```html
<div>
  <input type="text" v-focus placeholder="something">
</div>
```
```javascript
export default {
  directives: {
    focus: {
      inserted: function (el) {
        el.focus()
      }
    }
  }
}
```
now load this component or reload,the the animation  lose frame
