### ISSUE TITLE
Transitions classes are added after `before-enter` or `before-leave`

### ISSUE THREAD

**Issue by nicooprat** [vuejs/vue#8413]
### Version
2.5.16

### Reproduction link
[https://codesandbox.io/s/zq5mw2zk9x](https://codesandbox.io/s/zq5mw2zk9x)

### Steps to reproduce
1. Open browser console (to trigger the debugger)
2. Click on "Page 2"
3. Inspect elements inside `<main`>`

### What is expected?
The two children `<sections>` are supposed to have the transitions classes.

### What is actually happening?
The two children`<sections>` are already added but without any transition class, which are added on next tick. So the new `<section>` is visible on top on the old one for 1 frame, causing a flickering effect.

---
Remove this fix in `App.vue`:

```css
main > :first-child {
  z-index: 1; /* Prevent flickering on first frame when transition classes not added yet */
}
```

And navigate through the app to see the flicker effect.
