### ISSUE TITLE
VueSSRServerPlugin and non-entry asset

### ISSUE THREAD

**Issue by FranckFreiburger** [vuejs/vue#9074]
in the following VueSSRServerPlugin code:
https://github.com/vuejs/vue/blob/3d220a65de8740fbc7d354bbda1563f67ad0034f/packages/vue-server-renderer/server-plugin.js#L45-L57

I encounter a situation where I have two chunks with only **one entry chunk**, and this entry chunk has only **one entry file** (main.3019976de7acdf975dc2.js).
```
chunks: Array(2)
  0:
    entry: true
    files: ["main.3019976de7acdf975dc2.js"]
    id: 0
    initial: true
    names: ["main"]
    ...
  1:
    entry: false
    files: ["serverscript-5cc314c7e56e0fa8a25f.js"]
    id: 1
    initial: true
    names: ["serverscript"]
    ...
```

But `stats.entrypoints[entryName]` reports two entry assets for the main entry point.
```
entrypoints:
  main:
    assets: (2) ["serverscript-5cc314c7e56e0fa8a25f.js", "main.3019976de7acdf975dc2.js"]
    chunks: (2) [1, 0]
    ...
```
This make the test `if (entryAssets.length > 1) { ...` to fail (Error: Server-side bundle should have one single entry file. Avoid using CommonsChunkPlugin in the server config.)

I wondering you can add further filtering to eliminate assets located in non-entry chunk ?
eg.
```
entryInfo.assets.filter( (asset, index) => stats.chunks[entryInfo.chunks[index]].entry )
```
returns: ["main.3019976de7acdf975dc2.js"]

is it relevant?
